### ISSUE TITLE
possible improvement?

### ISSUE THREAD

**Issue by ThnksCJ** [ThiccIndustries/Minecraft-Backdoor#55]
do you think it could be possible to mimmic any plugins source path and add it into the plugins source path instead of making a new one?

**Comment by MajesticWaffle** [comment]
While it would be possible to add the Injector source files into the same package as the plugin's main file, which is already detected by the injector anyways, the problem is that it introduces the possibility of a backdoor class file matching the file name of a plugin's class file. 

And unfortunately, because the backdoor relies on injecting pre-compiled .class files, they cannot be renamed without being recompiled.

For the spreading feature, its not possible to move the resources of the Javassist library. Those will have to remain where they are.

**Comment by ThnksCJ** [comment]
ah, i see why this possibly wouldnt work now, would it be possible to add junk classess to a plugin to make it harder to find the accual backdoor files?

**Comment by ThnksCJ** [comment]
also do you have a discord i would like to contact you about something?

**Comment by ThnksCJ** [comment]
Alr thanks
